version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  version: "3.10"
  install:
    - requirements: requirements-docs.txt
    - method: pip
      path: .

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

formats:
  - pdf
  - epub

# Build documentation in the following branches
branches:
  - master
  - latest
  - stable

# Build documentation for the following tags
tags:
  - latest
  - stable
