name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'superpandas/**'
      - 'requirements-docs.txt'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'superpandas/**'
      - 'requirements-docs.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-docs.txt
        pip install -e .
        
    - name: Build documentation
      run: |
        cd docs
        make html
        
    - name: Check for broken links
      run: |
        pip install sphinx-linkcheck
        cd docs
        make linkcheck
        
    - name: Check for documentation warnings
      run: |
        cd docs
        make html SPHINXOPTS="-W --keep-going" 